apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-deployment
  namespace: harigold
  labels:
    app: hari
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hari
  template:
    metadata:
      labels:
        app: hari
    spec:
      containers:
      - name: goldapp
        image: haridev944/hari-gold-app
        ports:
        - containerPort: 80
