apiVersion: v1
kind: Service
metadata:
  name: hari-gold-app-service
  namespace: harigold
spec:
  selector:
    app: hari
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP
